volumes:
  cache:
    driver: local
  db-data:
    driver: local
  minio-data:
    driver: local
  pgAdmin-data:
    driver: local

services:
  api:
    container_name: 'lindaSelfGuruApi'
    build: ./
    links:
      - postgres
      - pgadmin
      - minio
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    restart: always
    container_name: postgresSelfGuru
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lxqtpr2021
    volumes:
      - db-data:/postgres

  pgadmin:
    container_name: pgAdminSelfGuru
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: lxqtpr@gmail.com
      PGADMIN_DEFAULT_PASSWORD: lxqtpr2021
    ports:
      - "5050:80"
    volumes:
      - pgAdmin-data:/pgadmin
  minio:
    image: minio/minio:latest
    container_name: minioSelfGuru
    restart: always
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server ~/minio --console-address :9090
    ports:
      - "9090:9090"
      - "9000:9000"
    volumes:
      - minio-data:/minio
  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass bHhxdHByMjAyMQ==
    volumes:
      - cache:/data